### ISSUE TITLE
Add Universal Module Definition

### ISSUE THREAD

**Issue by benjaminmcdonald** [DylanPiercey/set-dom#1]
https://github.com/umdjs/umd/blob/master/templates/amdWeb.js

(function (root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['b'], factory);
    } else {
        // Browser globals
        root.amdWeb = factory(root.b);
    }
}(this, function (b) {
    //use b in some fashion.

    // Just return a value to define the module export.
    // This example returns an object, but the module
    // can return a function as the exported value.
    return {};
}));

**Comment by DylanPiercey** [comment]
I added a dist file with the umd format, hopefully this is sufficient.
https://raw.githubusercontent.com/DylanPiercey/set-dom/master/dist/set-dom.js
