### ISSUE TITLE
Creating Releases tags.

### ISSUE THREAD

**Issue by devmondo** [DylanPiercey/set-dom#11]
hi again,

i think there is a need to create releases tags, for example when i tried to update the lib with jspm, nothing happened, i had to uninstall the lib and reinstall it to get the latest changes.

thanks in advanced.

**Comment by DylanPiercey** [comment]
Just created the first release tag. (Started using [np](https://github.com/sindresorhus/np) 😄).

**Comment by devmondo** [comment]
you rock 👍
