### ISSUE TITLE
weird data-key behavior and data-key or data-ignore not set in IE

### ISSUE THREAD

**Issue by devmondo** [DylanPiercey/set-dom#12]
hi Again,

maybe i am doing something wrong buti have this original DOM

```
<div id="mount" class="test">
    normal text
    <h1 data-key="1">first render</h1>
    <h1 data-key="2">first render duplicate</h1>
</div>
```
to diff with
```
<div id="mount" class="test">
    normal text
    <h1 data-key="2" >first render duplicate</h1>
    <h1 data-key="1">first render</h1>
</div>
```

as you see from above i just flipped `H1` elements, but what i get in result is below, you will see that `H1` with `data-key=2` inner html became empty.

```
<div id="mount" class="test">
    normal text
    <h1 data-key="2"></h1><h1 data-key="1">first render</h1>
</div>
```

the other issue is that `data-key` and `data-ignore` are never showing in the browser when using IE 11,10,9

i guess it is traced down to this line
https://github.com/DylanPiercey/set-dom/blob/master/lib/index.js#L107

in chrome b would result for example `id="mount"` but in IE it will result in `mount`.

thanks in advanced.

**Comment by DylanPiercey** [comment]
Hey I just tried to resolve this and got all tests running in ie10 so perhaps it is fixed now. Do you think you could check it out?

Also if it is still working do you think you could create a failing test case and post it here? If not thats okay.

**Comment by devmondo** [comment]
man, awesome, it is working perfectly with IE 11,10,9, Chrome

so all above issues are fixed.

do i still have to create something else to help as you mentioned above ?

**Comment by DylanPiercey** [comment]
No that's great to here. Glad it's working for you! I hope to have automated cross browser testing soon.

**Comment by devmondo** [comment]
thanks you so much man for the great work and support :)
