### ISSUE TITLE
Some cleanup

### ISSUE THREAD

**Issue by jmas** [DylanPiercey/set-dom#6]
Hello. Have an ideas about cleanup / update:
1. ES6;
2. `Node.DOCUMENT_NODE`, `Node.ELEMENT_NODE` (https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType);
3. `const KEY_ATTR_NAME = 'data-key'`;
4. JSDoc types is need to be aligned with real DOM entities (ex. `HTMLElement`, `Node`, `NamedNodeMap`, `NodeList`). WebStorm can't recognize types that currently used.

I started playing with your lib, and firstly did some above changes (https://gist.github.com/jmas/c483c29aa837ddee7f5039cea92ae8ce).

**Comment by DylanPiercey** [comment]
Thanks for the cleanup ideas, the commit you linked to looks good.

However I am not currently interested in using any es6+ features in set dom just to keep it simple. I would consider changing this once node gets proper module support.

Everything else though (es5-) looks great and I would gladly accept a pr.

**Comment by DylanPiercey** [comment]
Going to close this for now, but feel free to submit a PR whenever :).
