### ISSUE TITLE
working with Components

### ISSUE THREAD

**Issue by devmondo** [DylanPiercey/set-dom#8]
Hi, sorry for another question in short period of time,

but how can we implement the concept of components correctly with set-dom? what i mean is that let us take the below example
```
<div id="wrapper">
    <h1>header</h1>
    <component-parent>
        <div>dynamic text</div>
        <component-child-a></component-child-a>
        <component-child-b></component-child-b>
    </component-parent>
</div>
```

now if dynamic text change, it is no issue, but as you would expect the above  `component-child-a` and `component-child-b` HTML is just placeholder, when we parse the tags above we replace them with dynamic component's content ( same like react or any other framework), so let us say they will become as below
```
<div id="wrapper">
    <h1>header</h1>
    <component-parent>
        <div>dynamic text</div>
        <component-child-a>
            <h1>component content after parsing</h1>
        </component-child-a>
        <component-child-b>
            <component-child-c>component content after parsing</component-child-c>
        </component-child-b>
    </component-parent>
</div>
```
this problem now is that say we want to change `<div>dynamic text</div>` on parent component to ` <div>new dynamic text</div>` if we diff again, `component-child-a` and `component-child-b` will loose their dynamic injected content. the same would happen if we  click a button to inject component dynamically.

the point is that how to avoid that in your experience ? 

should set-dom have some option to ignore diffing elements if they start with a  tag name, attribute in ignore list somewhere, ? or set-dom already has solution for that ?

the other issue is that how to handle relationship between parent and child components from timing point of view, in simple words how do we guarantee if parent component had `attached` hook, and there is some code to communicate with child component or vice versa, both of them are available? 

i am talking the same as React components and child components and passing params to them.

thanks again in advanced :)

**Comment by DylanPiercey** [comment]
Since set-dom works with strings I just use functions that return strings as my components.

For example with [as-html](https://github.com/DylanPiercey/as-html).

### index.js
```js
import html from 'as-html'
import setDOM from 'set-dom'

import componentA from './a'
import componentB from './b'

setDOM(document, `
    <html>
        <head>...</head>
        <body>
            <div id="container">
                !${componentA(null, ['world'])}
                !${componentB({ message: 'world' })}
            </div>
        </body>
    </html>
`)
```

### a.js
```js
import html from 'as-html'

export default function componentA (props = {}, children = []) {
    return html`
        <h1>Hello !${children.join('')}</h1>
    `
}
```

### b.js
```js
import html from 'as-html'

export default function componentB (props = {}, children = []) {
    return html`
        <h1>Hello !${props.message}</h1>
    `
}
```

Does that make sense?

**Comment by devmondo** [comment]
you rock man! this is exactly how i tried it on my own earlier today, i am glad you confirmed this. 

the rest is mostly internal pluming on my side, i will continue experimenting and let you know in case of issues :+1:

**Comment by DylanPiercey** [comment]
Glad this works for you.

Also if you like JSX but don't like the bulk of react you can use set-dom with [vdo](https://github.com/DylanPiercey/vdo) which is a super lightweight JSX -> HTML library.

**Comment by devmondo** [comment]
thanks man, 

what i like about all your project is that the code is so easy to read and so small and elegant, and after seeing all big famous frameworks code and how big and complicated it is, one started to doubt that you cant do anything with simple code, but yours is a big proof about that, it is going back to the basics and avoid the bloat.
 
This allows us to integrate your pieces and create framework from it instead of using black boxes like angular and react. 

this sounds like a stretch for some people and they might say it is more complicated to emulate react or X framework and might say it is slow, but i am sick of those  down to 1 ms race benchmarks out there, plus how often you gonna need to move hundreds of DOM elements on a micro interval time span ? 

most apps are not Stock Financial Apps, and reality is that most Apps will do super fine with this approach, hence MorphDom, etc...

speaking of MorphDom, their lib is great, but i think it is little too much and i compared results between them and set-dom and there was very small marginal difference in performance that it is neglected, in fact set-dom was faster in many scenarios i did. the only nice part for me about MorphDom is diffing life cycle events.

i believe more people should use your excellent work ;)

**Comment by DylanPiercey** [comment]
Thank you, I very much appreciate your feedback and agree with all of your points. It is much harder to achieve minimalist frameworks than black box anything can happen frameworks in my opinion. I have spent so much time trying to figure out the absolute optimum balance between productivity, flexibility and bloat and try to put that into all of my projects.

Even [rill](https://github.com/rill-js/rill) my largest OS project is actually quite small. If you look at the bundle size of 38.8k it might look somewhat big but the reality is if you dig deeper it uses most of the browser shims provided by browserify (URL, querystring, eventlistener, process) which are all things that are likely in a browserified codebase anyway and these things actually take up the majority of the rill bundle. On top of that [react-router](https://github.com/ReactTraining/react-router), which is the closest thing to rill, is ~40kb and provides less features.

Thanks again for your praise and certainly don't hesitate to bring issues like this up again.

**Comment by devmondo** [comment]
man i read your rill article and checked the code, so beautiful, you are bringing back faith in Old School, Rock On!!!

**Comment by DylanPiercey** [comment]
Also I forgot to mention - At some point in the future I have what I think is a clean way to add life cycle events.

Basically I would set it up so that there would be two [custom events](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events) (mount, and dismount). My biggest hurdle though is that people typically people will want to know when a component mounts and dismounts (not individual elements) so I am trying to think of an elegant solution.

**Comment by devmondo** [comment]
great idea man, basically, i used your code in combination with [on-load](https://github.com/shama/on-load) for now and it works perfectly!

**Comment by DylanPiercey** [comment]
@devmondo with the #4.0 release keyed elements will now emit those custom events I mentioned earlier. Let me know if you have any issues with it!

**Comment by devmondo** [comment]
@DylanPiercey thank you very much man this is awesome!
