### ISSUE TITLE
Event Listeners handling

### ISSUE THREAD

**Issue by devmondo** [DylanPiercey/set-dom#9]
Hi again,

i am not sure how this should be approached, but if an element had an event listener attached to it when it is diffed or removed by set-dom i am not sure if events are cleared out, this could cause memory issues.

what is your view on this ?

**Comment by DylanPiercey** [comment]
@devmondo I use event delegation to get around this issue, check out https://github.com/component/delegate, or if you are using rill checkout https://github.com/rill-js/delegate.

Let me know if this works for you.

**Comment by devmondo** [comment]
@DylanPiercey,
thanks for the suggestion, do you mean if i assign events through those libs, when element is removed from or diffed in DOM, those libs will automatically clean up the handlers ?

**Comment by DylanPiercey** [comment]
That is correct, with event delegation you bind an event to a parent (in this case you want one that will never be removed like `document`) and then it adds an event listener to the parent that will delegate events that match the provided selector.

```js
import { bind } from 'component-delegate'

bind(document, '.my-class', 'click', e => {
 // Here the event listener was bound to document, but it matched .my-class.
})
```

Make sense?

**Comment by devmondo** [comment]
perfecto same like jquery !

i see what you did with rill there, very cleaver!!!

thanks again mate ;)

**Comment by DylanPiercey** [comment]
No problem, glad to help!
